module.exports = {
    ParameterError: require('./ParameterError'),
    DatabaseError: require('./DatabaseError'),
    NoReferencedRowError: require('./NoReferencedRowError'),
    NotMatchedError: require('./NotMatchedError'),
    AuthorizationError: require('./AuthorizationError'),
    TokenExpiredError: require('./TokenExpiredError'),
    DuplicatedEntryError: require('./DuplicatedEntryError'),
    MissPasswordError: require('./MissPasswordError'),
    NotFoundError: require('./NotFoundError'),
    NotCreatedError: require('./NotCreatedError'),
    NotUpdatedError: require('./NotUpdatedError'),
    NotDeletedError: require('./NotDeletedError'),
    ExistedUserError: require('./ExistedUserError'),
};
